FORMAT: 1A

# Activity Streams Chat API
Preliminary API for an Activity Streams-based chat application

## Users Collection [/users]

### List all users [GET]
+ Response 200 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "totalItems": 2,
            "itemsPerPage": 2,
            "items": [
                {
                    "@type": "Person",
                    "@id": "urn:activity-streams-chat:person:1"
                    "url": "https://activity-streams-chat-api.herokuapp.com/api/users/1"
                    "displayName": "William Shatner", 
                    "image": {
                        "@type": "Link",
                        "href": "http://shatner.gif"
                    }
                },
                {
                    "@type": "Person",
                    "@id": "urn:activity-streams-chat:person:2"
                    "url": "https://activity-streams-chat-api.herokuapp.com/api/users/2"
                    "displayName": "George Takei", 
                    "image": {
                        "@type": "Link",
                        "href": "http://takei.gif"
                    }
                }
            ]
        }

### Create a user [POST]
+ Request (application/json)

        { 
            "displayName": "Leonard Nimoy", 
            "image": "http://image.link" 
        }

+ Response 201 (application/json)

        {
            "@type": "Person",
            "@id": "urn:activity-streams-chat:person:3"
            "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
            "displayName": "Leonard Nimoy", 
            "image": {
                "@type": "Link",
                "href": "http://image.link"
            }
        }

## Current User [/users/me]

### Update current user [PUT]
+ Request (application/json)

        { 
            "displayName": "Leonard Simon Nimoy" 
        }

+ Response 200

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Update",
            "object": {
                "@type": "Person",
                "@id": "urn:activity-streams-chat:person:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                "displayName": "Leonard Simon Nimoy", 
                "image": {
                    "@type": "Link",
                    "href": "http://image.link"
                }
            }
        }

### Delete current user [DELETE]
+ Response 204

## User [/users/{user_id}]

+ Parameters
    + user_id (required, number, `3`) ... Numeric `id` of the User to perform action on.

### Get a user's details [GET]
+ Response 200 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Person",
            "@id": "urn:activity-streams-chat:person:3"
            "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
            "displayName": "Leonard Nimoy", 
            "image": {
                "@type": "Link",
                "href": "http://image.link"
            }
        }

## Rooms Collection [/rooms]

### List all rooms [GET]
+ Response 200 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "totalItems": 2,
            "itemsPerPage": 2,
            "items": [
                {
                    "@type": "Community",
                    "@id": "urn:activity-streams-chat:community:1"
                    "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/1"
                    "displayName": "Klingon Kar Talk", 
                },
                {
                    "@type": "Community",
                    "@id": "urn:activity-streams-chat:community:2"
                    "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/2"
                    "displayName": "Deep Space Forty Niners", 
                }
            ]
        }

### Create a room [POST]
+ Request (application/json)

        {
            "displayName": "Sushi Plans" 
        }

+ Response 201 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Create",
            "actor": {
                "@type": "Person",
                "@id": "urn:activity-streams-chat:person:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                "displayName": "Leonard Simon Nimoy", 
                "image": {
                    "@type": "Link",
                    "href": "http://image.link"
                }
            },
            "object": {
                "@type": "Community",
                "@id": "urn:activity-streams-chat:community:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/3"
                "displayName": "Sushi Plans", 
            }
        }

## Room [/rooms/{room_id}]

+ Parameters
    + room_id (required, number, `3`) ... Numeric `id` of the Room to perform action on.

### Retrieve a room's details [GET]
+ Response 200 (application/json)

        {
            "@type": "Community",
            "@id": "urn:activity-streams-chat:community:3"
            "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/3"
            "displayName": "Sushi Plans", 
        }

### Rename a room [PUT]
+ Request (application/json)

        { 
            "displayName": "Friday Sushi Plans"
        }

+ Response 200

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Update",
            "actor": {
                "@type": "Person",
                "@id": "urn:activity-streams-chat:person:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                "displayName": "Leonard Simon Nimoy", 
                "image": {
                    "@type": "Link",
                    "href": "http://image.link"
                }
            },
            "object": {
                "@type": "Community",
                "@id": "urn:activity-streams-chat:community:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/3"
                "displayName": "Friday Sushi Plans", 
            }
        }

### Delete a room [DELETE]
+ Response 200

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Delete",
            "actor": {
                "@type": "Person",
                "@id": "urn:activity-streams-chat:person:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                "displayName": "Leonard Simon Nimoy", 
                "image": {
                    "@type": "Link",
                    "href": "http://image.link"
                }
            },
            "object": {
                "@type": "Community",
                "@id": "urn:activity-streams-chat:community:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/3"
                "displayName": "Friday Sushi Plans", 
            }
        }

## Members Collection [/rooms/{room_id}/members]
The members that exist in a specified room

+ Parameters
    + room_id (required, number, `3`) ... Numeric `id` of the Room to perform action on.
    
### Retrieve the list of members in the room [GET]
+ Response 200 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "totalItems": 2,
            "itemsPerPage": 2,
            "items": [
                {
                    "@type": "Person",
                    "@id": "urn:activity-streams-chat:person:1"
                    "url": "https://activity-streams-chat-api.herokuapp.com/api/users/1"
                    "displayName": "William Shatner", 
                    "image": {
                        "@type": "Link",
                        "href": "http://shatner.gif"
                    }
                },
                {
                    "@type": "Person",
                    "@id": "urn:activity-streams-chat:person:2"
                    "url": "https://activity-streams-chat-api.herokuapp.com/api/users/2"
                    "displayName": "George Takei", 
                    "image": {
                        "@type": "Link",
                        "href": "http://takei.gif"
                    }
                }
            ]
        }

### Join a room [POST]
+ Response 201 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Join",
            "actor": {
                "@type": "Person",
                "@id": "urn:activity-streams-chat:person:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                "displayName": "Leonard Nimoy", 
                "image": {
                    "@type": "Link",
                    "href": "http://image.link"
                }
            },
            "object": {
                "@type": "Community",
                "@id": "urn:activity-streams-chat:community:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/3"
                "displayName": "Romulan battle plans", 
            }
        }

### Leave a room [DELETE]
+ Response 200 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Leave",
            "actor": {
                "@type": "Person",
                "@id": "urn:activity-streams-chat:person:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                "displayName": "Leonard Nimoy", 
                "image": {
                    "@type": "Link",
                    "href": "http://image.link"
                }
            },
            "object": {
                "@type": "Community",
                "@id": "urn:activity-streams-chat:community:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/rooms/3"
                "displayName": "Romulan battle plans", 
            }
        }

## Messages Collection [/rooms/{room_id}/messages{?before}]

+ Parameters
    + room_id (required, number, `3`) ... Numeric `id` of the Room get the messages from.

### Retrieve 50 messages in a room [GET]
+ Parameters
    + before (optional, number) ... If specified, get the 50 messages prior to this message id, if null, gets the most recent 50 messages

+ Response 200 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "totalItems": 2,
            "itemsPerPage": 2,
            "items": [
                {
                    "@type": "Post",
                    "actor": {
                        "@type": "Person",
                        "@id": "urn:activity-streams-chat:person:3"
                        "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                        "displayName": "Leonard Nimoy", 
                        "image": {
                            "@type": "Link",
                            "href": "http://image.link"
                        }
                    },
                    "object": { 
                        "@type": "Note",
                        "content": "Hey Sulu, up for sushi tonight?"
                    }
                }
                {
                    "@type": "Post",
                    "actor": {
                        "@type": "Person",
                        "@id": "urn:activity-streams-chat:person:2"
                        "url": "https://activity-streams-chat-api.herokuapp.com/api/users/2"
                        "displayName": "George Takei", 
                        "image": {
                            "@type": "Link",
                            "href": "http://takei.gif"
                        }
                    },
                    "object": { 
                        "@type": "Note",
                        "content": "Yeah, I'm always up for some good toro!"
                    }
                }
            ]
        }

### Create a message [POST]
+ Request (application/json)

        { 
            "content": "Meet at 7?"
        }
        
+ Response 201 (application/json)

        {
            "@context": "https://activity-streams-chat-api.herokuapp.com/api",
            "@type": "Post",
            "actor": {
                "@type": "Person",
                "@id": "urn:activity-streams-chat:person:3"
                "url": "https://activity-streams-chat-api.herokuapp.com/api/users/3"
                "displayName": "Leonard Nimoy", 
                "image": {
                    "@type": "Link",
                    "href": "http://image.link"
                }
            },
            "object": { 
                "@type": "Note",
                "content": "Meet at 7?"
            }
        }
